name: Track Positions and Deploy

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (minimum for GitHub)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  track-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Cache TypeScript build
      id: cache-dist
      uses: actions/cache@v4
      with:
        path: dist
        key: ${{ runner.os }}-tsc-${{ hashFiles('src/**/*.ts', 'tsconfig.json') }}
    
    - name: Cache position data
      uses: actions/cache@v4
      with:
        path: data/positions.json
        key: positions-${{ github.run_number }}
        restore-keys: |
          positions-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build TypeScript
      if: steps.cache-dist.outputs.cache-hit != 'true'
      run: npm run build
    
    - name: Run position tracker
      env:
        WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
        POSITION_ID: ${{ secrets.POSITION_ID }}
      run: npm run start:once
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: track-and-build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4